"""Central user-facing help texts."""


def tempo_analysis_help_text() -> str:
    """Explain tempo proposals and the required editorial review."""
    return (
        "BPM UND TEMPVORSCHLÄGE\n\n"
        "BPM (Beats pro Minute) beschreibt das musikalische Grundtempo. Die "
        "automatische Analyse verändert weder die Musikdatei noch deren Tags. "
        "Sie speichert ihr Ergebnis zunächst ausschließlich als Vorschlag.\n\n"
        "ANZEIGEN\n\n"
        "BPM-Vorschlag\n"
        "Das vom Analyseverfahren wahrscheinlichste Tempo. Ein vorhandener, "
        "manuell bestätigter Katalogwert wird dadurch nicht überschrieben.\n\n"
        "Alternative\n"
        "Eine ebenfalls plausible Tempoauslegung. Besonders häufig unterscheiden "
        "sich Vorschlag und Alternative um den Faktor zwei, zum Beispiel 120 und "
        "240 BPM. Das ist eine Halbtempo-/Doppeltempo-Interpretation desselben "
        "Rhythmus.\n\n"
        "Konfidenz\n"
        "Technische Einschätzung, wie eindeutig der BPM-Vorschlag ist. Auch eine "
        "hohe Konfidenz ersetzt keine Hörprüfung. Mittlere oder niedrige Werte "
        "sollten besonders sorgfältig geprüft werden.\n\n"
        "Rhythmusstabilität\n"
        "Bewertet, wie gleichmäßig die erkannten rhythmischen Impulse über die "
        "Aufnahme verteilt sind. Niedrigere Werte können bei Tempowechseln, langen "
        "Intros, Breaks, Liveaufnahmen oder komplexer Rhythmik entstehen.\n\n"
        "Experimenteller Energievorschlag\n"
        "Eine technische Schätzung der musikalischen Intensität. Energie ist nicht "
        "dasselbe wie Lautheit und bleibt ausdrücklich experimentell.\n\n"
        "Analyseverfahren und Version\n"
        "Dokumentieren, mit welchem Verfahren das Ergebnis erzeugt wurde. Dadurch "
        "kann DeckRelay später veraltete Analysen erkennen.\n\n"
        "WARNUNGEN\n\n"
        "Halb-/Doppeltempo-Alternative vorhanden\n"
        "Beide Werte passen zum erkannten Puls. Durch Anhören entscheiden, welcher "
        "Wert die musikalisch sinnvolle Zählweise beschreibt.\n\n"
        "Möglicher Tempowechsel oder instabiles Tempo\n"
        "Die Aufnahme besitzt kein durchgehend eindeutiges Taktraster. Das Ergebnis "
        "nicht ungeprüft übernehmen.\n\n"
        "Prüfung erforderlich\n"
        "Die technische Sicherheit reicht für eine automatische Bestätigung nicht "
        "aus. Der Vorschlag bleibt zur fachlichen Prüfung gespeichert.\n\n"
        "EMPFOHLENER ABLAUF\n\n"
        "1. Titel anhören und den BPM-Vorschlag mit dem wahrgenommenen Grundtempo "
        "vergleichen.\n"
        "2. Bei Halb-/Doppeltempo beide Werte gedanklich oder mitzählend prüfen.\n"
        "3. Passenden Vorschlag übernehmen oder den korrekten Wert manuell "
        "eintragen.\n"
        "4. Den Wert erst danach bestätigen. Manuell bestätigte Werte bleiben vor "
        "späteren automatischen Analysen geschützt."
    )
